# Generated by Django 3.2.8 on 2021-10-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
