# Generated by Django 3.2.8 on 2021-10-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211024_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_file',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_file',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
