# Generated by Django 3.2.8 on 2021-10-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211024_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_file',
        ),
    ]
