# Generated by Django 3.2.8 on 2021-10-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_address_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_file',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_file',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
