# Generated by Django 3.2.8 on 2021-10-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211024_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_file',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_file',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
