# Generated by Django 3.2.8 on 2021-10-23 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 11, 11, 34, 300651, tzinfo=utc), null=True)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Current',
            },
        ),
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 11, 11, 34, 300651, tzinfo=utc), null=True)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], max_length=20, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usertasks.current')),
            ],
            options={
                'verbose_name_plural': 'Deleted',
            },
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 11, 11, 34, 300651, tzinfo=utc), null=True)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], max_length=20, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usertasks.current')),
            ],
            options={
                'verbose_name_plural': 'Completed',
            },
        ),
    ]
