# Generated by Django 3.2.8 on 2021-10-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='current',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
